// ─────────────────────────────────────────────────────────────
// Weave AI — 가상 샘플 데이터 (전원 가상 인물, 실명·실기업 아님)
// 추천·적합도는 규칙 기반으로 생성된 데모 값이며 실제 AI 호출이 없다.
// ─────────────────────────────────────────────────────────────

export const EMPLOYEES = [
  { id: "E01", name: "김서연", dept: "디지털서비스팀", role: "백엔드 개발자", years: 5,
    skills: [["Java", 5], ["Spring Boot", 5], ["Oracle", 4], ["데이터 모델링", 4], ["Python", 2]],
    certs: ["정보처리기사", "SQLD"], projects: ["공공기관 민원 시스템 고도화", "지자체 데이터 개방 API"],
    edu: ["클린 코드와 리팩터링", "SQL 성능 튜닝"],
    wantRole: "데이터·AI 서비스 개발자", wantProject: "AI·공공데이터 융합 프로젝트",
    available: "2026.09.01", updated: "2026.07.28", aiConsent: true, recvRec: true, signals: [] },
  { id: "E02", name: "이준호", dept: "플랫폼개발팀", role: "백엔드 개발자", years: 7,
    skills: [["Java", 5], ["Spring Boot", 4], ["MSA", 4], ["Kubernetes", 3], ["Oracle", 3]],
    certs: ["정보처리기사"], projects: ["금융권 계정계 전환", "공공 클라우드 전환 지원"],
    edu: ["대용량 트래픽 설계"], wantRole: "테크리드", wantProject: "대규모 플랫폼 구축",
    available: "2026.09.15", updated: "2026.08.02", aiConsent: true, recvRec: true, signals: [] },
  { id: "E03", name: "박지민", dept: "데이터팀", role: "데이터 분석가", years: 3,
    skills: [["Python", 4], ["SQL", 4], ["Tableau", 4], ["통계 분석", 3]],
    certs: ["ADsP"], projects: ["고객 이탈 분석", "매출 대시보드 구축"],
    edu: ["실무 통계"], wantRole: "데이터 사이언티스트", wantProject: "예측 모델링 프로젝트",
    available: "2026.10.01", updated: "2026.05.11", aiConsent: true, recvRec: true,
    signals: ["최근 프로젝트 기회 부족", "역량정보 갱신 필요"] },
  { id: "E04", name: "최현우", dept: "디지털서비스팀", role: "프런트엔드 개발자", years: 4,
    skills: [["React", 5], ["TypeScript", 4], ["Next.js", 4], ["접근성", 3]],
    certs: [], projects: ["대민 포털 개편", "사내 디자인시스템 구축"],
    edu: ["웹 접근성 심화"], wantRole: "프로덕트 엔지니어", wantProject: "신규 서비스 런칭",
    available: "2026.09.01", updated: "2026.07.30", aiConsent: true, recvRec: true, signals: [] },
  { id: "E05", name: "정다은", dept: "데이터팀", role: "데이터 엔지니어", years: 6,
    skills: [["Python", 4], ["Spark", 4], ["Airflow", 4], ["데이터 모델링", 5], ["Oracle", 4]],
    certs: ["SQLP"], projects: ["전사 데이터 웨어하우스 구축", "공공데이터 수집 파이프라인"],
    edu: ["데이터 거버넌스"], wantRole: "데이터 플랫폼 아키텍트", wantProject: "차세대 데이터 플랫폼",
    available: "2026.09.01", updated: "2026.08.05", aiConsent: true, recvRec: true, signals: [] },
  { id: "E06", name: "한상윤", dept: "PMO", role: "프로젝트 매니저", years: 11,
    skills: [["프로젝트 관리", 5], ["요구사항 분석", 5], ["공공 프로젝트", 5], ["Java", 2]],
    certs: ["PMP", "정보시스템감리원"], projects: ["공공기관 차세대 시스템 PM", "지자체 통합 플랫폼 PM"],
    edu: ["애자일 리더십"], wantRole: "포트폴리오 매니저", wantProject: "대형 공공 SI",
    available: "2026.09.01", updated: "2026.07.15", aiConsent: true, recvRec: true, signals: [] },
  { id: "E07", name: "오세라", dept: "서비스기획팀", role: "서비스 기획자", years: 5,
    skills: [["서비스 기획", 5], ["데이터 리터러시", 3], ["UX 리서치", 4]],
    certs: [], projects: ["모바일 민원 서비스 기획", "공공 마이데이터 기획"],
    edu: ["프로덕트 디스커버리"], wantRole: "프로덕트 오너", wantProject: "AI 서비스 기획",
    available: "2026.09.10", updated: "2026.08.01", aiConsent: true, recvRec: true, signals: [] },
  { id: "E08", name: "임태규", dept: "인프라팀", role: "클라우드 엔지니어", years: 8,
    skills: [["AWS", 5], ["Kubernetes", 4], ["Terraform", 4], ["보안", 3]],
    certs: ["AWS SA Pro"], projects: ["공공 클라우드 전환", "재해복구 체계 구축"],
    edu: ["제로 트러스트 보안"], wantRole: "클라우드 아키텍트", wantProject: "하이브리드 클라우드",
    available: "2026.11.01", updated: "2026.06.20", aiConsent: false, recvRec: false,
    signals: ["희망 직무와 현재 업무 불일치"] },
  { id: "E09", name: "송하늘", dept: "플랫폼개발팀", role: "백엔드 개발자", years: 2,
    skills: [["Java", 3], ["Spring Boot", 3], ["MySQL", 3]],
    certs: ["정보처리기사"], projects: ["사내 인증 서비스 개선"],
    edu: ["신입 온보딩 과정"], wantRole: "백엔드 개발자", wantProject: "공공 프로젝트 참여",
    available: "2026.09.01", updated: "2026.04.02", aiConsent: true, recvRec: true,
    signals: ["장기간 교육 참여 부재", "역량정보 갱신 필요"] },
  { id: "E10", name: "배진우", dept: "AI연구팀", role: "ML 엔지니어", years: 4,
    skills: [["Python", 5], ["머신러닝", 4], ["MLOps", 3], ["Java", 2]],
    certs: ["빅데이터분석기사"], projects: ["수요 예측 모델 구축", "문서 분류 자동화"],
    edu: ["LLM 활용 실무"], wantRole: "AI 솔루션 아키텍트", wantProject: "공공 AI 융합",
    available: "2026.09.20", updated: "2026.08.03", aiConsent: true, recvRec: true, signals: [] },
  { id: "E11", name: "문가영", dept: "AI연구팀", role: "AI 서비스 개발자", years: 6,
    skills: [["Python", 5], ["AI API 활용", 5], ["머신러닝", 4], ["서비스 설계", 4]],
    certs: [], projects: ["대화형 민원 안내 서비스", "AI 문서요약 도입"],
    edu: ["AI 윤리와 거버넌스"], wantRole: "AI 프로덕트 리드", wantProject: "공공 AI 서비스",
    available: "2026.09.01", updated: "2026.07.22", aiConsent: true, recvRec: true, signals: [] },
  { id: "E12", name: "신동혁", dept: "품질관리팀", role: "QA 엔지니어", years: 9,
    skills: [["테스트 자동화", 5], ["성능 테스트", 4], ["Python", 3]],
    certs: ["ISTQB"], projects: ["차세대 시스템 품질 검증", "테스트 자동화 체계 구축"],
    edu: ["시프트레프트 테스팅"], wantRole: "QA 리드", wantProject: "품질 엔지니어링 표준화",
    available: "2026.09.01", updated: "2026.07.10", aiConsent: true, recvRec: true,
    signals: ["보유역량 대비 낮은 역할 활용도", "경력개발 면담 필요"] },
  { id: "E13", name: "김민지", dept: "마케팅팀", role: "퍼포먼스 마케터", years: 4,
    skills: [["GA4·데이터 분석", 4], ["콘텐츠 기획", 4], ["SQL", 3], ["광고 운영", 5]],
    certs: ["GAIQ"], projects: ["신규 서비스 론칭 캠페인", "리텐션 개선 실험"],
    edu: ["그로스 마케팅 실무"], wantRole: "그로스 리드", wantProject: "데이터 기반 마케팅 자동화",
    available: "2026.10.01", updated: "2026.07.18", aiConsent: true, recvRec: true, signals: [] },
  { id: "E14", name: "유정한", dept: "인사팀", role: "HRD 담당", years: 6,
    skills: [["교육 기획", 5], ["HR 데이터 분석", 3], ["조직개발", 4], ["퍼실리테이션", 4]],
    certs: ["평생교육사"], projects: ["직무교육 체계 개편", "온보딩 프로그램 구축"],
    edu: ["피플 애널리틱스 입문"], wantRole: "피플 애널리틱스 리드", wantProject: "역량 데이터 기반 교육 설계",
    available: "2026.09.01", updated: "2026.08.06", aiConsent: true, recvRec: true, signals: [] },
  { id: "E15", name: "조은비", dept: "디자인팀", role: "프로덕트 디자이너", years: 5,
    skills: [["Figma", 5], ["UX 리서치", 4], ["디자인시스템", 4], ["프로토타이핑", 4]],
    certs: [], projects: ["대민 포털 UX 개편", "디자인시스템 2.0"],
    edu: ["데이터 기반 UX"], wantRole: "프로덕트 디자인 리드", wantProject: "AI 서비스 UX 설계",
    available: "2026.09.15", updated: "2026.07.25", aiConsent: true, recvRec: true, signals: [] },
  { id: "E16", name: "장우석", dept: "영업본부", role: "B2B 영업", years: 8,
    skills: [["B2B 영업", 5], ["제안서 작성", 4], ["CRM 활용", 4], ["공공 조달", 4]],
    certs: [], projects: ["공공기관 수주 3건", "파트너 채널 확대"],
    edu: ["전략 영업 과정"], wantRole: "영업 팀장", wantProject: "대형 공공 수주",
    available: "2026.09.01", updated: "2026.06.30", aiConsent: true, recvRec: true, signals: [] },
  { id: "E17", name: "권나래", dept: "디지털서비스팀", role: "백엔드 개발자", years: 6,
    skills: [["Java", 4], ["Spring Boot", 4], ["Oracle", 4], ["MySQL", 3], ["MSA", 3]],
    certs: ["정보처리기사"], projects: ["대민 포털 API 재설계"], edu: ["JPA 실무"],
    wantRole: "백엔드 아키텍트", wantProject: "레거시 전환", available: "2026.09.01", updated: "2026.07.20", aiConsent: true, recvRec: true, signals: [] },
  { id: "E18", name: "홍서우", dept: "디지털서비스팀", role: "프런트엔드 개발자", years: 3,
    skills: [["React", 4], ["TypeScript", 4], ["Next.js", 3], ["접근성", 3], ["Figma", 2]],
    certs: [], projects: ["민원 신청 화면 개편"], edu: ["프런트엔드 성능 최적화"],
    wantRole: "프로덕트 엔지니어", wantProject: "신규 서비스", available: "2026.09.01", updated: "2026.08.01", aiConsent: true, recvRec: true, signals: [] },
  { id: "E19", name: "남기훈", dept: "플랫폼개발팀", role: "백엔드 개발자", years: 9,
    skills: [["Java", 5], ["MSA", 5], ["Kubernetes", 4], ["대용량 처리", 4]],
    certs: ["정보처리기사"], projects: ["플랫폼 트래픽 개선"], edu: ["분산 시스템 설계"],
    wantRole: "테크리드", wantProject: "차세대 플랫폼", available: "2026.10.01", updated: "2026.07.28", aiConsent: true, recvRec: true, signals: [] },
  { id: "E20", name: "차예린", dept: "플랫폼개발팀", role: "플랫폼 엔지니어", years: 4,
    skills: [["Kubernetes", 4], ["Terraform", 3], ["Java", 3], ["보안", 3]],
    certs: ["CKA"], projects: ["사내 배포 파이프라인 구축"], edu: ["플랫폼 엔지니어링"],
    wantRole: "플랫폼 아키텍트", wantProject: "내부 개발자 플랫폼", available: "2026.09.10", updated: "2026.08.04", aiConsent: true, recvRec: true, signals: [] },
  { id: "E21", name: "백승주", dept: "데이터팀", role: "데이터 분석가", years: 5,
    skills: [["SQL", 5], ["Python", 4], ["Tableau", 3], ["통계 분석", 4]],
    certs: ["ADP"], projects: ["서비스 지표 체계 수립"], edu: ["인과추론 입문"],
    wantRole: "데이터 사이언티스트", wantProject: "실험 플랫폼", available: "2026.09.01", updated: "2026.07.31", aiConsent: true, recvRec: true, signals: [] },
  { id: "E22", name: "여수민", dept: "데이터팀", role: "데이터 엔지니어", years: 3,
    skills: [["Python", 3], ["Spark", 3], ["SQL", 4], ["Airflow", 3]],
    certs: ["SQLD"], projects: ["로그 수집 파이프라인"], edu: ["데이터 모델링 기초"],
    wantRole: "데이터 엔지니어", wantProject: "데이터 레이크", available: "2026.09.01", updated: "2026.05.20", aiConsent: true, recvRec: true,
    signals: ["역량정보 갱신 필요"] },
  { id: "E23", name: "표진호", dept: "PMO", role: "프로젝트 매니저", years: 7,
    skills: [["프로젝트 관리", 5], ["요구사항 분석", 4], ["공공 프로젝트", 4], ["일정 관리", 4]],
    certs: ["PMP"], projects: ["지자체 통합 플랫폼"], edu: ["리스크 관리"],
    wantRole: "PMO 리드", wantProject: "대형 공공 SI", available: "2026.09.01", updated: "2026.07.12", aiConsent: true, recvRec: true, signals: [] },
  { id: "E24", name: "구다혜", dept: "PMO", role: "PMO 담당", years: 4,
    skills: [["프로젝트 관리", 3], ["요구사항 분석", 3], ["SQL", 3], ["일정 관리", 4]],
    certs: [], projects: ["사업 관리 표준화"], edu: ["애자일 기초"],
    wantRole: "프로젝트 매니저", wantProject: "공공 프로젝트", available: "2026.09.20", updated: "2026.08.02", aiConsent: true, recvRec: true, signals: [] },
  { id: "E25", name: "심우재", dept: "서비스기획팀", role: "서비스 기획자", years: 7,
    skills: [["서비스 기획", 5], ["UX 리서치", 3], ["데이터 리터러시", 4], ["요구사항 분석", 4]],
    certs: [], projects: ["마이데이터 서비스 기획"], edu: ["프로덕트 전략"],
    wantRole: "프로덕트 오너", wantProject: "AI 서비스 기획", available: "2026.09.01", updated: "2026.07.26", aiConsent: true, recvRec: true, signals: [] },
  { id: "E26", name: "양소윤", dept: "서비스기획팀", role: "서비스 기획자", years: 2,
    skills: [["서비스 기획", 3], ["콘텐츠 기획", 3], ["데이터 리터러시", 2]],
    certs: [], projects: ["고객 여정 리서치"], edu: ["신입 기획자 과정"],
    wantRole: "서비스 기획자", wantProject: "신규 서비스", available: "2026.09.01", updated: "2026.04.18", aiConsent: true, recvRec: true,
    signals: ["장기간 교육 참여 부재"] },
  { id: "E27", name: "노현석", dept: "인프라팀", role: "클라우드 엔지니어", years: 5,
    skills: [["AWS", 4], ["Terraform", 4], ["Kubernetes", 3], ["보안", 3]],
    certs: ["AWS SAA"], projects: ["멀티 계정 거버넌스"], edu: ["IaC 실무"],
    wantRole: "클라우드 아키텍트", wantProject: "하이브리드 클라우드", available: "2026.09.01", updated: "2026.07.29", aiConsent: true, recvRec: true, signals: [] },
  { id: "E28", name: "진하율", dept: "인프라팀", role: "보안 엔지니어", years: 7,
    skills: [["보안", 5], ["AWS", 3], ["Kubernetes", 3], ["Python", 3]],
    certs: ["CISSP"], projects: ["제로 트러스트 전환"], edu: ["클라우드 보안"],
    wantRole: "보안 아키텍트", wantProject: "정보보호 체계 고도화", available: "2026.10.01", updated: "2026.08.05", aiConsent: true, recvRec: true, signals: [] },
  { id: "E29", name: "고은결", dept: "AI연구팀", role: "ML 엔지니어", years: 3,
    skills: [["Python", 4], ["머신러닝", 3], ["MLOps", 2], ["SQL", 3]],
    certs: ["빅데이터분석기사"], projects: ["이상 탐지 모델 실험"], edu: ["딥러닝 기초"],
    wantRole: "ML 엔지니어", wantProject: "예측 모델 고도화", available: "2026.09.01", updated: "2026.08.01", aiConsent: true, recvRec: true, signals: [] },
  { id: "E30", name: "류지완", dept: "AI연구팀", role: "AI 서비스 개발자", years: 4,
    skills: [["AI API 활용", 4], ["Python", 4], ["서비스 설계", 3], ["React", 2]],
    certs: [], projects: ["문서 자동분류 서비스"], edu: ["LLM 애플리케이션 개발"],
    wantRole: "AI 서비스 개발자", wantProject: "생성형 AI 서비스", available: "2026.09.15", updated: "2026.07.24", aiConsent: false, recvRec: false, signals: [] },
  { id: "E31", name: "은세영", dept: "품질관리팀", role: "QA 엔지니어", years: 4,
    skills: [["테스트 자동화", 4], ["성능 테스트", 3], ["Python", 3], ["SQL", 3]],
    certs: ["ISTQB"], projects: ["회귀 테스트 자동화"], edu: ["테스트 설계 기법"],
    wantRole: "QA 리드", wantProject: "품질 자동화", available: "2026.09.01", updated: "2026.07.15", aiConsent: true, recvRec: true, signals: [] },
  { id: "E32", name: "지태오", dept: "품질관리팀", role: "품질 담당", years: 11,
    skills: [["품질 관리", 5], ["테스트 자동화", 3], ["요구사항 분석", 4], ["프로젝트 관리", 3]],
    certs: [], projects: ["품질 표준 수립"], edu: ["품질경영"],
    wantRole: "품질 총괄", wantProject: "전사 품질 체계", available: "2026.09.01", updated: "2026.06.28", aiConsent: true, recvRec: true, signals: [] },
  { id: "E33", name: "명지후", dept: "마케팅팀", role: "콘텐츠 마케터", years: 3,
    skills: [["콘텐츠 기획", 4], ["GA4·데이터 분석", 3], ["광고 운영", 3]],
    certs: [], projects: ["브랜드 콘텐츠 시리즈"], edu: ["콘텐츠 전략"],
    wantRole: "콘텐츠 리드", wantProject: "브랜드 캠페인", available: "2026.09.01", updated: "2026.07.30", aiConsent: true, recvRec: true, signals: [] },
  { id: "E34", name: "안유빈", dept: "마케팅팀", role: "그로스 마케터", years: 6,
    skills: [["GA4·데이터 분석", 5], ["SQL", 4], ["광고 운영", 4], ["Python", 2]],
    certs: ["GAIQ"], projects: ["퍼널 개선 실험"], edu: ["그로스 실험 설계"],
    wantRole: "그로스 리드", wantProject: "마케팅 자동화", available: "2026.10.01", updated: "2026.08.03", aiConsent: true, recvRec: true, signals: [] },
  { id: "E35", name: "천보라", dept: "인사팀", role: "인사 담당", years: 8,
    skills: [["인사운영", 5], ["HR 데이터 분석", 4], ["노무", 4], ["SQL", 3]],
    certs: ["공인노무사 1차"], projects: ["직무급 전환 설계"], edu: ["HR 애널리틱스"],
    wantRole: "인사 기획 리드", wantProject: "인사제도 개편", available: "2026.09.01", updated: "2026.07.22", aiConsent: true, recvRec: true, signals: [] },
  { id: "E36", name: "허강민", dept: "인사팀", role: "채용 담당", years: 4,
    skills: [["채용", 4], ["HR 데이터 분석", 3], ["교육 기획", 3], ["퍼실리테이션", 3]],
    certs: [], projects: ["구조화 면접 도입"], edu: ["선발 도구 설계"],
    wantRole: "채용 리드", wantProject: "채용 브랜딩", available: "2026.09.01", updated: "2026.08.06", aiConsent: true, recvRec: true, signals: [] },
  { id: "E37", name: "석하람", dept: "디자인팀", role: "UX 디자이너", years: 4,
    skills: [["UX 리서치", 5], ["Figma", 4], ["프로토타이핑", 3], ["접근성", 3]],
    certs: [], projects: ["사용성 테스트 체계화"], edu: ["리서치 방법론"],
    wantRole: "UX 리드", wantProject: "AI 서비스 UX", available: "2026.09.10", updated: "2026.07.27", aiConsent: true, recvRec: true, signals: [] },
  { id: "E38", name: "봉시현", dept: "디자인팀", role: "UI 디자이너", years: 2,
    skills: [["Figma", 4], ["디자인시스템", 3], ["프로토타이핑", 3]],
    certs: [], projects: ["디자인시스템 컴포넌트 확장"], edu: ["UI 모션 기초"],
    wantRole: "프로덕트 디자이너", wantProject: "디자인시스템 3.0", available: "2026.09.01", updated: "2026.05.02", aiConsent: true, recvRec: true,
    signals: ["역량정보 갱신 필요"] },
  { id: "E39", name: "위도현", dept: "영업본부", role: "B2B 영업", years: 5,
    skills: [["B2B 영업", 4], ["CRM 활용", 4], ["제안서 작성", 3], ["공공 조달", 3]],
    certs: [], projects: ["민간 채널 신규 개척"], edu: ["솔루션 세일즈"],
    wantRole: "영업 매니저", wantProject: "민간 시장 확대", available: "2026.09.01", updated: "2026.07.19", aiConsent: true, recvRec: true, signals: [] },
  { id: "E40", name: "탁서윤", dept: "영업본부", role: "영업 기획", years: 6,
    skills: [["제안서 작성", 5], ["공공 조달", 4], ["SQL", 3], ["프로젝트 관리", 3]],
    certs: [], projects: ["수주 전략 수립"], edu: ["공공 입찰 실무"],
    wantRole: "영업 기획 리드", wantProject: "대형 공공 수주", available: "2026.09.20", updated: "2026.08.02", aiConsent: true, recvRec: true, signals: [] },
];

export const PROJECT = {
  name: "공공기관 차세대 데이터 플랫폼 구축",
  period: "2026.09. ~ 2027.03.", headcount: 6, start: "2026.09.01",
  required: ["Java", "Spring Boot", "Oracle", "데이터 모델링", "공공 프로젝트 경험"],
  preferred: ["프로젝트 리딩 경험", "SQLD", "AI 활용 경험"],
};

// 규칙 기반 매칭 결과 (요구조건-역량 일치 정도, 가상 값)
export const SEARCH_RESULTS = [
  { id: "E01", fit: 96,
    reason: "요구역량 5개 중 5개 보유. 공공 프로젝트 2건, SQLD 보유, 희망 프로젝트와 일치.",
    matched: ["Java", "Spring Boot", "Oracle", "데이터 모델링", "공공 프로젝트 경험"],
    missing: [], similar: ["공공기관 민원 시스템 고도화", "지자체 데이터 개방 API"], wantMatch: true },
  { id: "E02", fit: 91,
    reason: "요구역량 4개 보유, MSA·클라우드 전환 경험. 데이터 모델링 심화 경험은 보완 필요.",
    matched: ["Java", "Spring Boot", "Oracle", "공공 프로젝트 경험"],
    missing: ["데이터 모델링(심화)"], similar: ["공공 클라우드 전환 지원"], wantMatch: false },
  { id: "E05", fit: 86,
    reason: "데이터 모델링 최고 수준, 공공데이터 파이프라인 경험. Java 백엔드 실무는 보완 필요.",
    matched: ["Oracle", "데이터 모델링", "공공 프로젝트 경험"],
    missing: ["Java(실무)", "Spring Boot"], similar: ["공공데이터 수집 파이프라인"], wantMatch: true },
  { id: "E10", fit: 79,
    reason: "AI 활용 우대사항 충족, Python 상급. 백엔드 핵심 스택은 기초 수준이라 역할 조정 필요.",
    matched: ["공공 프로젝트 경험(유사)"],
    missing: ["Java(실무)", "Spring Boot", "Oracle"], similar: ["수요 예측 모델 구축"], wantMatch: true },
];

export const TEAM_INIT = [
  { slot: "PM", id: "E06", why: "공공 대형 프로젝트 PM 2회, PMP 보유", gap: "없음" },
  { slot: "백엔드 개발자", id: "E01", why: "요구 스택 전부 보유, 공공 경험·SQLD", gap: "없음" },
  { slot: "백엔드 개발자", id: "E02", why: "대용량 처리·클라우드 전환 경험", gap: "데이터 모델링 심화" },
  { slot: "데이터 담당자", id: "E05", why: "DW 구축·공공데이터 파이프라인 경험", gap: "없음" },
  { slot: "AI 담당자", id: "E11", why: "AI API 서비스화 경험, 공공 AI 서비스 이력", gap: "없음" },
  { slot: "서비스 기획자", id: "E07", why: "공공 마이데이터 기획 경험", gap: "데이터 리터러시 보강" },
];
// 슬롯별 대체 후보 — 원 추천자와 겹치지 않게 지정
export const ALTERNATES = { "백엔드 개발자": "E09", "AI 담당자": "E10", "데이터 담당자": "E03", "PM": "E12", "서비스 기획자": "E15" };

/* ── 현재 수행 업무와 잔여 일정 ──────────────────────────────
   심층 인터뷰: "월간 일정과 현재 수행업무를 함께 봐야 투입 가능 여부를 안다"
   load = 현재 업무가 차지하는 비중(%), until = 현재 업무 종료 예정일 */
export const CURRENT_WORK = {
  E01: { task: "민원 시스템 고도화 · 안정화", load: 60, until: "2026.08.31" },
  E02: { task: "공공 클라우드 전환 2차", load: 90, until: "2026.09.12" },
  E05: { task: "데이터 표준화 TF", load: 40, until: "2026.08.20" },
  E06: { task: "지자체 통합포털 마무리", load: 50, until: "2026.08.29" },
  E07: { task: "마이데이터 서비스 기획", load: 30, until: "2026.08.14" },
  E11: { task: "AI 상담 서비스 운영", load: 70, until: "2026.08.31" },
};
export const workOf = (id) => CURRENT_WORK[id] || null;

/* ── 역할별 직무 전문가(SME) ──────────────────────────────
   심층 인터뷰: "추천 결과를 그 일을 아는 사람이 한 번 봐야 한다" */
export const SME_REVIEWERS = {
  "PM": "PMO 팀장",
  "백엔드 개발자": "플랫폼개발팀 수석",
  "데이터 담당자": "데이터팀 리드",
  "AI 담당자": "AI서비스팀 리드",
  "서비스 기획자": "디지털기획팀 리드",
};
export const smeOf = (slot) => SME_REVIEWERS[slot] || "해당 직무 책임자";

export const GAPS = [
  { skill: "Python", cur: 2, target: 4, why: "데이터·AI 서비스의 공용 언어", course: "실무자를 위한 Python 데이터 분석", hours: 24, link: "공공데이터 분석 과제" },
  { skill: "머신러닝 기초", cur: 1, target: 3, why: "추천·예측 기능의 원리 이해", course: "머신러닝 입문", hours: 30, link: "수요 예측 모델 참여" },
  { skill: "AI API 활용", cur: 1, target: 4, why: "생성형 AI 기능을 서비스에 결합", course: "생성형 AI API 활용", hours: 16, link: "AI 민원 안내 고도화" },
  { skill: "데이터 시각화", cur: 2, target: 3, why: "분석 결과를 의사결정자에게 전달", course: "AI 서비스 설계 프로젝트", hours: 20, link: "경영 대시보드 구축" },
  { skill: "MLOps 기초", cur: 1, target: 2, why: "모델 배포·운영 파이프라인 이해", course: "MLOps 기초", hours: 18, link: "모델 서빙 표준화" },
];

// 목표 직무별 역량 격차 — 프로필에서 희망 직무를 바꾸면 이 표가 바뀐다
export const GAPS_BY_ROLE = {
  "데이터·AI 서비스 개발자": GAPS,
  "데이터 엔지니어": [
    { skill: "Spark", cur: 1, target: 4, why: "대용량 배치 처리의 표준 엔진", course: "Spark 기반 데이터 처리", hours: 28, link: "데이터 웨어하우스 고도화" },
    { skill: "Airflow", cur: 1, target: 4, why: "파이프라인 스케줄링과 의존성 관리", course: "워크플로 오케스트레이션 실무", hours: 20, link: "공공데이터 수집 파이프라인" },
    { skill: "Python", cur: 2, target: 4, why: "데이터 파이프라인 구현 언어", course: "실무자를 위한 Python 데이터 분석", hours: 24, link: "공공데이터 분석 과제" },
    { skill: "데이터 거버넌스", cur: 1, target: 3, why: "품질·계보·보존정책 관리", course: "데이터 거버넌스 입문", hours: 16, link: "전사 데이터 표준화" },
  ],
  "백엔드 아키텍트": [
    { skill: "MSA 설계", cur: 2, target: 4, why: "서비스 분해와 경계 설계", course: "마이크로서비스 아키텍처", hours: 26, link: "차세대 플랫폼 아키텍처" },
    { skill: "Kubernetes", cur: 1, target: 3, why: "컨테이너 운영 환경 이해", course: "쿠버네티스 운영 기초", hours: 22, link: "클라우드 전환 2차" },
    { skill: "대용량 처리", cur: 2, target: 4, why: "트래픽·데이터 규모 대응 설계", course: "대용량 트래픽 설계", hours: 20, link: "레거시 전환 2차" },
  ],
  "테크리드": [
    { skill: "아키텍처 설계", cur: 2, target: 4, why: "모듈 경계와 기술 의사결정 주도", course: "소프트웨어 아키텍처 실무", hours: 24, link: "차세대 플랫폼 모듈 리딩" },
    { skill: "코드 리뷰·멘토링", cur: 3, target: 4, why: "팀 전체의 품질 기준 유지", course: "테크리드 워크숍", hours: 12, link: "신입 온보딩 멘토" },
    { skill: "이해관계자 관리", cur: 1, target: 3, why: "기획·운영 부서와의 조율", course: "기술 커뮤니케이션", hours: 14, link: "공공 프로젝트 협업" },
  ],
};

export const PATHS = [
  { key: "A", steps: ["백엔드 개발자", "AI 서비스 개발자", "AI 솔루션 아키텍트"],
    needs: ["Python", "AI API 활용", "머신러닝 기초"], courses: ["생성형 AI API 활용", "머신러닝 입문"],
    projects: ["AI·공공데이터 융합"], period: "약 18~24개월", match: 78 },
  { key: "B", steps: ["백엔드 개발자", "데이터 엔지니어", "데이터 플랫폼 아키텍트"],
    needs: ["Spark", "Airflow", "데이터 거버넌스"], courses: ["데이터 파이프라인 실무"],
    projects: ["차세대 데이터 플랫폼"], period: "약 24개월", match: 71 },
  { key: "C", steps: ["백엔드 개발자", "테크리드", "프로젝트 매니저"],
    needs: ["아키텍처 설계", "리딩 경험", "이해관계자 관리"], courses: ["테크리드 워크숍"],
    projects: ["모듈 리딩 역할 수행"], period: "약 24~36개월", match: 64 },
];

export const RETENTION = [
  { id: "E03", status: "프로젝트 기회 추천", support: "예측 모델링 프로젝트 후보 추천, 분석 직무 공모 안내" },
  { id: "E08", status: "경력상담 권장", support: "클라우드 아키텍트 전환 경로 면담, 희망 직무 재확인" },
  { id: "E09", status: "교육지원 검토", support: "백엔드 심화 교육 지원, 공공 프로젝트 참관 기회" },
  { id: "E12", status: "성장지원 검토", support: "QA 리드 역할 시범 부여, 품질 표준화 과제 리딩 기회" },
];

export const empById = (id) => EMPLOYEES.find((e) => e.id === id);

/* ── 심층 인터뷰에서 도출된 요건과 화면 반영 상태 ──────────────────
   status: done 반영 · partial 부분 반영 · todo 후속 과제 */
export const INTERVIEW_REQS = [
  { area: "인재데이터", req: "경력·자격뿐 아니라 실제 수행업무, 프로젝트 경험, 희망직무를 통합 관리",
    voice: "경력·자격·발령이력만으로는 현업이 요구하는 실질 역량을 확인하기 어렵다", screen: "인재 프로필", key: "profiles", status: "done" },
  { area: "인재데이터", req: "본인이 입력한 정보와 AI가 추론한 정보를 구분해 표시",
    voice: "자기평가는 과대·과소 입력될 수 있다", screen: "내 역량 프로필", key: "profile", status: "done" },
  { area: "인재데이터", req: "자격증·교육이수·프로젝트 이력 등 객관적 증빙과 연계",
    voice: "일회성 교육만으로 높은 수준을 입력할 수 있다", screen: "내 역량 프로필", key: "profile", status: "partial" },
  { area: "인재데이터", req: "정보의 정기 갱신과 최신성 표시",
    voice: "필요할 때 자료를 취합하는 방식으로 파악하고 있다", screen: "인재 프로필", key: "profiles", status: "done" },
  { area: "탐색·매칭", req: "부서·경력·보유기술 기준의 사내 인재 탐색",
    voice: "TF 구성, 정기전보, 인력 Pool 구성에 쓸 수 있다", screen: "AI 인재 탐색", key: "search", status: "done" },
  { area: "탐색·매칭", req: "적합도만이 아니라 구체적 추천 근거 제시",
    voice: "어떤 경력이 어떤 기준으로 적합하다고 판단됐는지 알아야 한다", screen: "AI 인재 탐색 · 추천 근거", key: "search", status: "done" },
  { area: "탐색·매칭", req: "투입 가능 시기와 현재 업무 일정 확인",
    voice: "월간 일정과 현재 수행업무를 함께 봐야 투입 가능 여부를 안다", screen: "프로젝트 매칭 · 투입 가능", key: "matching", status: "done" },
  { area: "탐색·매칭", req: "직무 표준화 정도에 따른 단계적 적용",
    voice: "사업장별 특수성이 큰 직무는 AI가 요구사항을 반영하기 어렵다", screen: "-", key: null, status: "todo" },
  { area: "의사결정", req: "AI가 보지 못하는 정성 요인을 담당자가 확인",
    voice: "업무스타일, 팀 관계, 근무지역 선호는 정량화하기 어렵다", screen: "프로젝트 매칭 · 확인 항목", key: "matching", status: "done" },
  { area: "의사결정", req: "최종 결정은 사람이 하되 자의적 판단을 막는 기록 절차",
    voice: "AI 추천과 다른 결정을 내렸다면 사유를 기록해야 한다", screen: "결정 기록", key: "decisions", status: "done" },
  { area: "의사결정", req: "관리자·직무전문가(SME)의 추천 결과 검토",
    voice: "도입 초기에는 현업 전문가 검토단이 필요하다", screen: "프로젝트 매칭 · SME 검토", key: "matching", status: "done" },
  { area: "공정성", req: "경력구간에 따라 추천 기준을 달리 적용",
    voice: "주니어는 기초역량과 학습 가능성을 더 봐야 한다", screen: "공정성·신뢰센터", key: "fairness", status: "partial" },
  { area: "공정성", req: "추천 기회가 특정 인원·부서에 집중되는지 정기 점검",
    voice: "기회를 많이 받은 사람에게 계속 유리해질 수 있다", screen: "공정성·신뢰센터", key: "fairness", status: "done" },
  { area: "공정성", req: "직무관련성이 불명확한 정보를 추천에서 배제",
    voice: "성별·연령·학력은 차별을 강화할 수 있다", screen: "공정성·신뢰센터", key: "fairness", status: "done" },
  { area: "공정성", req: "이의제기와 재검토 절차, 처리 결과 안내",
    voice: "추천되거나 제외된 근거를 확인하고 다툴 수 있어야 한다", screen: "내 역량 프로필", key: "profile", status: "partial" },
  { area: "수용성", req: "평가·인사상 불이익과 분리, 목적별 접근권한 구분",
    voice: "평가와 연동되면 노조 반발과 입력 회피가 생긴다", screen: "공정성·신뢰센터", key: "fairness", status: "partial" },
  { area: "수용성", req: "통제가 아닌 성장지원으로 읽히는 표현 사용",
    voice: "'저성과자'라는 표현은 통제 도구라는 인상을 준다", screen: "인재 유지관리", key: "retention", status: "done" },
  { area: "교육", req: "교육과정을 직무·숙련도별로 체계화",
    voice: "레벨별로 분류돼 있지 않으면 정확한 추천이 어렵다", screen: "성장 로드맵", key: "training", status: "partial" },
  { area: "교육", req: "내부교육 외에 외부교육·프로젝트·멘토링까지 연계",
    voice: "공통역량 교육만으로는 직무개발을 지원하지 못한다", screen: "성장 로드맵", key: "training", status: "done" },
  { area: "운영", req: "기존 ERP·그룹웨어 인사시스템과 연계",
    voice: "중복 입력과 관리 부담을 줄여야 한다", screen: "시스템 안내", key: "about", status: "partial" },
  { area: "운영", req: "부서별 업무량 조사와 연계한 적정인원 산정",
    voice: "인력운영 계획 수립에 쓰려면 필요하다", screen: "-", key: null, status: "todo" },
];

/* ── 결정 기록: AI 추천과 최종 결정의 일치 여부 (가상 데모) ── */
export const DECISIONS = [
  { date: "2026.08.04", project: "차세대 데이터 플랫폼", slot: "데이터 엔지니어",
    rec: "E05", final: "E05", match: true, reason: "", by: "PMO 팀장" },
  { date: "2026.08.04", project: "차세대 데이터 플랫폼", slot: "백엔드 개발자",
    rec: "E01", final: "E02", match: false, cat: "일정 중복",
    reason: "1순위 후보가 기존 프로젝트 종료 전이라 투입 시점이 맞지 않음", by: "PMO 팀장" },
  { date: "2026.07.29", project: "AI 비전 검사 도입", slot: "AI 담당자",
    rec: "E10", final: "E11", match: false, cat: "본인 의사",
    reason: "1순위 후보가 현재 담당 과제 마무리를 희망하여 본인 동의를 얻지 못함", by: "AI연구팀장" },
  { date: "2026.07.22", project: "공공 마이데이터", slot: "서비스 기획자",
    rec: "E07", final: "E07", match: true, reason: "", by: "서비스기획팀장" },
  { date: "2026.07.15", project: "사내 인증 서비스 개선", slot: "백엔드 개발자",
    rec: "E02", final: "E09", match: false, cat: "성장 기회",
    reason: "난이도가 적정하여 주니어에게 경험 기회를 부여하는 것이 낫다고 판단", by: "플랫폼개발팀장" },
  { date: "2026.07.08", project: "인사제도 개편", slot: "HR 담당자",
    rec: "E14", final: "E14", match: true, reason: "", by: "인사팀장" },
  { date: "2026.07.01", project: "전사 데이터 웨어하우스", slot: "데이터 담당자",
    rec: "E03", final: "E05", match: false, cat: "역량 판단 차이",
    reason: "요구역량 중 파이프라인 운영 경험이 실제로는 부족하다고 현업이 판단", by: "데이터팀장" },
  { date: "2026.06.24", project: "대민 포털 개편", slot: "프런트엔드 개발자",
    rec: "E04", final: "E04", match: true, reason: "", by: "디지털서비스팀장" },
];

/* ── AI 추천에 반영되지 않는 정성 요인 (담당자 확인 항목) ── */
export const BLIND_SPOTS = [
  ["본인의 이동·참여 의사", "추천 대상에게 직접 확인해야 합니다"],
  ["팀 구성과 협업 관계", "기존 팀원과의 조합은 데이터에 없습니다"],
  ["근무지역 선호", "사업장이 여러 곳이면 배치 수용성에 크게 작용합니다"],
  ["현재 업무 일정과 부하", "투입 가능 시점만으로는 실제 여력을 알 수 없습니다"],
  ["사업장·조직별 특수성", "같은 직무명이라도 실제 수행업무가 다를 수 있습니다"],
];

/* ── 직무를 직군으로 묶는 표 (이탈 위험 분석용) ── */
export const ROLE_FAMILY = {
  "백엔드 개발자": "IT개발", "프런트엔드 개발자": "IT개발", "플랫폼 엔지니어": "IT개발",
  "데이터 분석가": "데이터·AI", "데이터 엔지니어": "데이터·AI", "ML 엔지니어": "데이터·AI", "AI 서비스 개발자": "데이터·AI",
  "클라우드 엔지니어": "인프라·보안", "보안 엔지니어": "인프라·보안",
  "프로젝트 매니저": "기획·PM", "PMO 담당": "기획·PM", "서비스 기획자": "기획·PM",
  "QA 엔지니어": "품질", "품질 담당": "품질",
  "퍼포먼스 마케터": "마케팅", "콘텐츠 마케터": "마케팅", "그로스 마케터": "마케팅",
  "HRD 담당": "인사", "인사 담당": "인사", "채용 담당": "인사",
  "프로덕트 디자이너": "디자인", "UX 디자이너": "디자인", "UI 디자이너": "디자인",
  "B2B 영업": "영업", "영업 기획": "영업",
};

/* 직군별 이직률과 권고 대안.
   rate 는 산업 동향 탭의 이직률 구조를 참고한 예시값이며 공표 통계가 아니다. */
export const FAMILY_RISK = {
  "데이터·AI": { rate: 7.1, why: "AI·데이터 인력 수요가 공급을 크게 앞선다",
    action: "핵심 파이프라인 문서화, 모델 운영 2인 페어 편성, 경력경로 조기 제시" },
  "마케팅": { rate: 6.8, why: "성과 지표가 외부에 드러나 이직 제안을 자주 받는다",
    action: "캠페인 운영 매뉴얼화, 데이터 접근권한 승계 절차 마련" },
  "IT개발": { rate: 6.4, why: "동일 기술 스택의 시장 수요가 넓다",
    action: "코드 리뷰 의무화로 지식 분산, 주니어 페어 프로그래밍 운영" },
  "디자인": { rate: 5.9, why: "포트폴리오 기반 이동이 활발하다",
    action: "디자인시스템으로 산출물 표준화, 컴포넌트 문서 유지" },
  "영업": { rate: 5.4, why: "고객 관계가 개인에게 귀속되기 쉽다",
    action: "CRM 기록 의무화, 주요 고객 복수 담당제" },
  "기획·PM": { rate: 4.6, why: "프로젝트 종료 시점에 이동이 몰린다",
    action: "산출물 인수인계 체크리스트, 차기 과제 사전 배정" },
  "인프라·보안": { rate: 4.2, why: "자격 보유자가 적어 대체 채용이 오래 걸린다",
    action: "구성 정보 코드화(IaC), 권한 관리 이중화" },
  "품질": { rate: 3.9, why: "상대적으로 이동이 적으나 대체 인력을 찾기 어렵다",
    action: "테스트 자산 공유, 품질 기준 문서화" },
  "인사": { rate: 3.4, why: "제도 운영 지식이 개인에게 축적된다",
    action: "제도 운영 이력 기록, 연간 업무 캘린더 공유" },
};
